########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }
    - { name: Tools, url: "tools.html" }

  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }
    - { name: Tools, url: "tools.html" }

######################### Default Parameters ###########################

# logo
logo: "/assets/images/logo.png"
# meta data
author: "Ajsi"
description: "Contextual AI Writer for blogging. Complete AI blogging toolkit. Writes blog articles with relevant images. SEO optimised content. Free & Open source AI writer."
# google analitycs ID
google_analitycs_id: G-ELVN8KPTGT
# contact form action
contact_form_action: "#" # contact form works with : https://formspree.io
# copyright
copyright: "Copyright &copy; 2024 [Themefisher] &copy; Alwrity"

# preloader
preloader:
  enable: true
  preloader: "" # use png, jpg, svg or gif format

# search
search:
  enable: true

############################## Social Site ##########################
social:
  - name: "facebook"
    icon: "ti-facebook" # themify icon pack https://themify.me/themify-icons
    link: "https://github.com/AJaySi/AI-Blog-Writer"

  - name: "twitter"
    icon: "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
    link: "#"

  - name: "github"
    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
    link: "https://github.com/AJaySi/AI-Blog-Writer"

  - name: "linkedin"
    icon: "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link: "#"
